Fix

diff --git a/tool/fetch_or_ask b/tool/fetch_or_ask
--- a/tool/fetch_or_ask
+++ b/tool/fetch_or_ask
@@ -27,11 +27,16 @@ fetch_or_ask() {
         return
     fi
 
-    # Если указана только одна переменная, сохраняем значение в файл .env
+    # Если указана только одна переменная, проверяем её наличие в файле .env
     if [[ $# -eq 1 ]]; then
         local param="$1"
-        read -p "Enter value for $param (or press Enter to skip): " value
-        [[ -n "$value" ]] && printf "%s=%s\n" "$param" "$value" >> "$env_file"
+        existing_value=$(grep "^$param=" "$env_file" | cut -d= -f2)
+        if [[ -n $existing_value ]]; then
+            value=$existing_value
+        else
+            read -p "Enter value for $param (or press Enter to skip): " value
+            [[ -n "$value" ]] && printf "%s=%s\n" "$param" "$value" >> "$env_file"
+        fi
     else
         # Формируем путь к каталогу и имя файла
         local directory="./data"
@@ -45,18 +50,18 @@ fetch_or_ask() {
         # Защита от пустого filename
         [[ -z $filename ]] && { echo "Filename is empty."; exit 1; }
 
-        mkdir -p "$directory/$filename" || { echo "Failed to create directory $directory/$filename"; exit 1; }
+        mkdir -p "$directory" || { echo "Failed to create directory $directory"; exit 1; }
 
         # Проверяем, есть ли уже значение в файле
-        if [[ -f "$directory/$filename/$server_id" ]]; then
-            existing_value=$(<"$directory/$filename/$server_id")
+        if [[ -f "$directory/$server_id" ]]; then
+            existing_value=$(<"$directory/$server_id")
         fi
 
         if [[ -n $existing_value ]]; then
             value=$existing_value
         else
             read -p "Enter value for $filename (or press Enter to skip): " value
-            [[ -n "$value" ]] && printf "%s\n" "$value" > "$directory/$filename/$server_id"
+            [[ -n "$value" ]] && printf "%s\n" "$value" > "$directory/$server_id"
         fi
 
         export "$filename=$value"
